version: '3.4'
services:
  nightscout:
    image: dhermanns/rpi-nightscout:latest
    environment:
      TZ: Europe/Berlin
      MONGO_CONNECTION: mongodb://mongo:27017/nightscout
      API_SECRET: mypassword123
      BG_HIGH: 220
      BG_LOW: 60
      BG_TARGET_TOP: 180
      BG_TARGET_BOTTOM: 80
      INSECURE_USE_HTTP: "true"
#      SSL_KEY: /var/opt/ssl/server.key
#      SSL_CERT: /var/opt/ssl/serverchain.crt
#      SSL_CA: /var/opt/ssl/cachain.crt
      AUTH_DEFAULT_ROLES: readable devicestatus-upload
      ENABLE: alexa rawbg
    ports:
      - "1337:1337"
    depends_on:
      - mongo
    volumes:
      - /home/pi/docker/rpi-nightscout:/var/opt/ssl/:ro
    restart: always
  mongo:
    image: arm64v8/mongo:latest
    volumes:
      - ./data:/data/db                                                                      
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
      - "28017:28017"
    restart: always
